trigger:
    - master

pr: none

resources:
    - repo: self

variables:
    - group: public-npm
    - name: envName
      value: "brandup-ui"
    - name: version-major
      value: "2"
    - name: version-minor
      value: "0"

name: $(version-major).$(version-minor).$(rev:r)

pool:
    name: Test

stages:
    - stage: "Build"
      displayName: "Build"
      jobs:
          - job: "BuildNpm"
            displayName: "Build, test and pack"
            pool:
                name: Test
                workspace:
                    clean: all
            steps:
                - script: |
                      echo "Begin build $(Build.BuildNumber)!"
                  displayName: "print variables"

                - checkout: self
                  clean: "true"
                  persistCredentials: "true"

                - task: UseNode@1
                  displayName: use node 22.x
                  inputs:
                      version: 22.x
                      checkLatest: true

                - script: npm run i
                  displayName: "npm install"

                - script: npm run build
                  displayName: "packages npm build"

                - script: npm run test
                  displayName: "packages npm test"

                - script: npm run npm:version $(Build.BuildNumber)
                  displayName: "packages npm version"

                - script: npm run npm:cleanup
                  displayName: "packages npm cleanup"

                - script: npm run npm:pack --pack-destination "$(Build.ArtifactStagingDirectory)"
                  displayName: "packages npm pack"

                - publish: $(Build.ArtifactStagingDirectory)
                  displayName: publish artifact
                  condition: succeededOrFailed()
                  artifact: npm

    - stage: Production
      displayName: Deploy stage
      dependsOn: Build
      jobs:
          - deployment: Production
            condition: succeeded()
            displayName: "NPM"
            pool:
                name: Test
            environment: $(envName)
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - download: current
                              displayName: "download artifacts"
                              artifact: npm

                            - task: ExtractFiles@1
                              displayName: "unzip brandup-ui"
                              inputs:
                                  archiveFilePatterns: "$(Pipeline.Workspace)/npm/brandup-ui-$(Build.BuildNumber).tgz"
                                  destinationFolder: "$(Pipeline.Workspace)/npmout/brandup-ui"
                                  cleanDestinationFolder: true
                                  overwriteExistingFiles: true

                            - task: ExtractFiles@1
                              displayName: "unzip brandup-ui-dom"
                              inputs:
                                  archiveFilePatterns: "$(Pipeline.Workspace)/npm/brandup-ui-dom-$(Build.BuildNumber).tgz"
                                  destinationFolder: "$(Pipeline.Workspace)/npmout/brandup-ui-dom"
                                  cleanDestinationFolder: true
                                  overwriteExistingFiles: true

                            - task: ExtractFiles@1
                              displayName: "unzip brandup-ui-ajax"
                              inputs:
                                  archiveFilePatterns: "$(Pipeline.Workspace)/npm/brandup-ui-ajax-$(Build.BuildNumber).tgz"
                                  destinationFolder: "$(Pipeline.Workspace)/npmout/brandup-ui-ajax"
                                  cleanDestinationFolder: true
                                  overwriteExistingFiles: true

                            - task: ExtractFiles@1
                              displayName: "unzip brandup-ui-helpers"
                              inputs:
                                  archiveFilePatterns: "$(Pipeline.Workspace)/npm/brandup-ui-helpers-$(Build.BuildNumber).tgz"
                                  destinationFolder: "$(Pipeline.Workspace)/npmout/brandup-ui-helpers"
                                  cleanDestinationFolder: true
                                  overwriteExistingFiles: true

                            - task: ExtractFiles@1
                              displayName: "unzip brandup-ui-app"
                              inputs:
                                  archiveFilePatterns: "$(Pipeline.Workspace)/npm/brandup-ui-app-$(Build.BuildNumber).tgz"
                                  destinationFolder: "$(Pipeline.Workspace)/npmout/brandup-ui-app"
                                  cleanDestinationFolder: true
                                  overwriteExistingFiles: true

                            - task: ExtractFiles@1
                              displayName: "unzip brandup-ui-i18n"
                              inputs:
                                  archiveFilePatterns: "$(Pipeline.Workspace)/npm/brandup-ui-i18n-$(Build.BuildNumber).tgz"
                                  destinationFolder: "$(Pipeline.Workspace)/npmout/brandup-ui-i18n"
                                  cleanDestinationFolder: true
                                  overwriteExistingFiles: true

                            - task: UseNode@1
                              displayName: use node 22.x
                              inputs:
                                  version: 22.x
                                  checkLatest: true

                            # npmAuthenticate adds the token of the service connection to this file.
                            - script: echo registry=https://registry.npmjs.org/> "$(Pipeline.Workspace)/.npmrc"
                              displayName: "create .npmrc"

                            - task: npmAuthenticate@0
                              displayName: "npm authenticate"
                              inputs:
                                  workingFile: "$(Pipeline.Workspace)/.npmrc"
                                  customEndpoint: "$(publish-npm-credentials)"

                            # brandup-ui

                            - script: npm publish --userconfig "$(Pipeline.Workspace)/.npmrc"
                              displayName: "publish brandup-ui"
                              workingDirectory: "$(Pipeline.Workspace)/npmout/brandup-ui/package"

                            # brandup-ui-dom

                            - script: npm publish --userconfig "$(Pipeline.Workspace)/.npmrc"
                              displayName: "publish brandup-ui-dom"
                              workingDirectory: "$(Pipeline.Workspace)/npmout/brandup-ui-dom/package"

                            # brandup-ui-ajax

                            - script: npm publish --userconfig "$(Pipeline.Workspace)/.npmrc"
                              displayName: "publish brandup-ui-ajax"
                              workingDirectory: "$(Pipeline.Workspace)/npmout/brandup-ui-ajax/package"

                            # brandup-ui-helpers

                            - script: npm publish --userconfig "$(Pipeline.Workspace)/.npmrc"
                              displayName: "publish brandup-ui-helpers"
                              workingDirectory: "$(Pipeline.Workspace)/npmout/brandup-ui-helpers/package"

                            # brandup-ui-app

                            - script: npm publish --userconfig "$(Pipeline.Workspace)/.npmrc"
                              displayName: "publish brandup-ui-app"
                              workingDirectory: "$(Pipeline.Workspace)/npmout/brandup-ui-app/package"

                            # brandup-ui-i18n

                            - script: npm publish --userconfig "$(Pipeline.Workspace)/.npmrc"
                              displayName: "publish brandup-ui-i18n"
                              workingDirectory: "$(Pipeline.Workspace)/npmout/brandup-ui-i18n/package"

          - job: GitTag
            displayName: "Add git tag"
            dependsOn: [Production]
            condition: succeeded()
            steps:
                - checkout: self
                  clean: "true"
                  persistCredentials: "true"

                - script: |
                      echo Tagging $(Build.Repository.Name) with $(Build.BuildNumber)
                      git config user.name "AzureDevOps Agent"
                      git tag "$(Build.BuildNumber)" --force
                      git push origin "$(Build.BuildNumber)" --force
                  displayName: set git tag
